from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_name_url>\w+)/$',
        views.category, name='category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_url>\w+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/update/$', views.profile_update, name='profile_update'),
    url(r'^goto/$', views.track_url, name='track_url'),
    url(r'^like_category/$', views.like_category, name='like_category'),
    url(r'^suggest_category/$',
        views.suggest_category, name='suggest_category'),
    url(r'^check_new_username/$',
        views.check_new_username, name='check_new_username'),
    url(r'^profile/change_password/$',
        views.change_password, name='change_password'),
    url(r'^profile/delete/$', views.delete_user, name='delete_user'),
    url(r'^page/(?P<page_id>\d+)/delete/$',
        views.delete_page, name='delete_page'),
    url(r'^page/(?P<page_id>\d+)/edit/$',
        views.edit_page, name='edit_page'),
    url(r'^category/(?P<category_url>\w+)/delete/$',
        views.delete_category, name='delete_category'),
    url(r'^category/(?P<category_url>\w+)/edit/$',
        views.edit_category, name='edit_category'),
    )
